log_level = "INFO"
dry_run = true
s3_bucket = "webgwas"
s3_result_path = "results"
sqlite_db = "sqlite:///backend.db"
n_workers = 2
fit_quality_file = "prod_data/fit_quality.parquet"
root_data_directory = "prod_data"

[indirect_gwas]
