lru_cache_size = 10
s3_bucket = "webgwas-ohio"
cohort_paths = [
  "test_data/cohort1"
  "test_data/cohort2"
  "test_data/ukb_wb_100k_reduced_anon"
]

[indirect_gwas]
num_threads = 1
chunk_size = 10000
capacity = 5
compress = true
quiet = false
