---
- name: Compile backend locally
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    dependencies:
      - webgwas
  tasks:
    # TODO: This should use git so that ansible checks if the repo has changed
    - name: Compile backend
      shell: |
        rm -rf webgwas-backend
        git clone --depth 1 https://github.com/zietzm/webgwas-backend.git
        cd webgwas-backend
        export TARGET_CC=aarch64-unknown-linux-gnu-gcc
        export TARGET_FC=aarch64-unknown-linux-gnu-gfortran
        export TARGET_AR=aarch64-unknown-linux-gnu-ar
        export TARGET_RANLIB=aarch64-unknown-linux-gnu-ranlib
        export BLIS_CONFNAME=cortexa57
        cargo zigbuild --release --target aarch64-unknown-linux-gnu
        mv target/aarch64-unknown-linux-gnu/release/webgwas-backend ../webgwas_backend
      args:
        creates: "webgwas_backend"

- name: Deploy WebGWAS
  hosts: webgwas
  become: yes
  vars:
    nginx_conf_path: "/etc/nginx/conf.d/webgwas.conf"
    nginx_basic_conf_file: "nginx-basic.conf"
    nginx_conf_file: "nginx.conf"
  tasks:
    - name: Update and upgrade packages
      dnf:
        update_cache: yes
        name: '*'
        state: latest
    
    - name: Install required packages
      dnf:
        name:
          - nginx
          - perl-FindBin
          - perl-core
          - tmux
          - htop
          - sqlite.aarch64
        state: present

    - name: Copy Nginx config file
      template:
        src: "{{ nginx_basic_conf_file }}.j2"
        dest: "{{ nginx_conf_path }}"
        owner: root
        group: root
        mode: '0644'
      notify: Reload Nginx

    - name: Ensure default Nginx config is removed
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      notify: Reload Nginx

    - name: Ensure Nginx is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Obtain and install SSL certificate
      shell: 
        uvx --with certbot --with certbot-nginx certbot --nginx -d api.webgwas.org -d www.api.webgwas.org --non-interactive --agree-tos --email michael.zietz@gmail.com
      args:
        executable: /bin/bash
        creates: /etc/letsencrypt/live/api.webgwas.org/fullchain.pem

    - name: Ensure Certbot renew timer is enabled
      shell: |
        echo "0 0,12 * * * root /opt/certbot/bin/python -c 'import random; import time; time.sleep(random.random() * 3600)' && sudo certbot renew -q" | sudo tee -a /etc/crontab > /dev/null

    - name: Copy full Nginx config file
      template:
        src: "{{ nginx_conf_file }}.j2"
        dest: "{{ nginx_conf_path }}"
        owner: root
        group: root
        mode: '0644'
      notify: Reload Nginx

    - name: Sync data from S3 to EC2
      shell: |
        aws s3 sync s3://webgwas/prod_data /home/ec2-user/prod_data --delete
        aws s3 cp s3://webgwas/backend.db /home/ec2-user/backend.db

    - name: copy backend binary
      copy:
        src: webgwas_backend
        dest: /home/ec2-user/webgwas_backend

    - name: make the backend executable
      file:
        path: /home/ec2-user/webgwas_backend
        mode: '0755'

    - name: copy settings file
      copy:
        src: webgwas-backend/settings.toml
        dest: /home/ec2-user/settings.toml

    - name: Copy backend systemd service file
      copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Restart the backend systemd service
      systemd:
        name: backend
        state: restarted

    - name: Systemd reload
      systemd:
        daemon_reload: yes

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
